version: '3'

services: 
  nginx:
    build: .
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - conf:/etc/letsencrypt
      - web:/var/www/html
    networks: 
      - soa
  
  certbot:
    image: certbot/certbot
    volumes: 
      - conf:/etc/letsencrypt
      - web:/var/www/html
    depends_on: 
      - nginx
    networks: 
      - soa
    command: certonly --webroot --webroot-path=/var/www/html --email 59070025@it.kmitl.ac.th --agree-tos --no-eff-email --force-renewal -d soa.smartfishermans.com

volumes: 
  conf:
  web:

networks: 
  soa: